import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#0b1221",
        "surface-container-lowest": "#0d0f0f",
        "on-secondary-fixed": "#241a00",
        "surface-bright": "#38393a",
        "on-surface": "#e2e2e2",
        "inverse-surface": "#e2e2e2",
        "surface-container-high": "#282a2b",
        "surface-container-low": "#1a1c1c",
        "on-error": "#690005",
        "tertiary-container": "#11130b",
        "primary-fixed-dim": "#c0c6db",
        "on-secondary-fixed-variant": "#574500",
        "surface": "#f9f9f9",
        "outline": "#909097",
        "on-surface-variant": "#c6c6cd",
        "on-primary-container": "#777d90",
        "inverse-primary": "#575e70",
        "on-error-container": "#ffdad6",
        "secondary": "#e9c349",
        "surface-container-highest": "#333535",
        "on-tertiary-fixed-variant": "#46483d",
        "on-tertiary": "#2f3128",
        "on-background": "#0b1221",
        "secondary-container": "#af8d11",
        "on-tertiary-fixed": "#1b1c14",
        "secondary-fixed": "#ffe088",
        "surface-dim": "#f9f9f9",
        "primary-fixed": "#dce2f8",
        "tertiary": "#c7c7ba",
        "on-secondary-container": "#342800",
        "error": "#ffb4ab",
        "primary": "#c0c6db",
        "on-primary-fixed-variant": "#404758",
        "on-secondary": "#3c2f00",
        "tertiary-fixed-dim": "#c7c7ba",
        "on-tertiary-container": "#7d7e72",
        "surface-variant": "#333535",
        "on-primary": "#293041",
        "on-primary-fixed": "#151b2b",
        "error-container": "#93000a",
        "surface-tint": "#c0c6db",
        "inverse-on-surface": "#2f3131",
        "outline-variant": "#45464c",
        "background": "#f9f9f9",
        "surface-container": "#1e2020",
        "secondary-fixed-dim": "#e9c349",
        "tertiary-fixed": "#e3e3d5",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "container-max": "1440px",
        "margin-desktop": "80px",
        "section-gap": "120px",
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        serif: ["Playfair Display", "serif"],
        sans: ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
    },
  },
  plugins: [],
};

export default config;
